---
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-ready
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - key: '.status.phase'
      operator: 'In'
      values:
      - 'Pending'
    - key: '.metadata.deletionTimestamp'
      operator: 'DoesNotExist'
  delay:
    durationMilliseconds: 1000
  next:
    statusTemplate: |
      {{ $now := Now }}
      conditions:
      - lastProbeTime: null
        lastTransitionTime: {{ $now | Quote }}
        status: "True"
        type: Initialized
      - lastProbeTime: null
        lastTransitionTime: {{ $now | Quote }}
        status: "True"
        type: Ready
      - lastProbeTime: null
        lastTransitionTime: {{ $now | Quote }}
        status: "True"
        type: ContainersReady
      - lastProbeTime: null
        lastTransitionTime: {{ $now | Quote }}
        status: "True"
        type: PodScheduled
      containerStatuses:
      {{ range $_, $container := .spec.containers }}
      - image: {{ $container.image | Quote }}
        name: {{ $container.name | Quote }}
        ready: true
        restartCount: 0
        started: true
        state:
          running:
            startedAt: {{ $now | Quote }}
      {{ end }}
      hostIP: 10.0.0.1
      podIP: 10.0.0.{{ .metadata.uid | Hash | Mod 256 }}
      phase: Running

---
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-complete
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
      - key: '.metadata.deletionTimestamp'
        operator: 'Exists'
      - key: '.status.phase'
        operator: 'NotIn'
        values:
          - 'Succeeded'
  delay:
    durationMilliseconds: 500
  next:
    delete: true
